# Generated by Django 5.1.3 on 2024-11-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
