# Generated by Django 5.1.3 on 2024-11-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('d_o_b', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default='O', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit_date', models.DateField()),
                ('last_visit_time', models.TimeField()),
                ('next_appointment', models.BooleanField(default=False)),
                ('next_appointment_date', models.DateField()),
                ('next_appointment_time', models.TimeField()),
                ('next_appointment_procedure', models.TextField()),
                ('last_visit_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_last_appointment', to='doctors.doctor')),
                ('last_visit_procedures', models.ManyToManyField(blank=True, to='doctors.procedures')),
                ('next_appointment_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_next_appointment', to='doctors.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointment', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date_time', models.DateTimeField()),
                ('doctors_notes', models.TextField()),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_seen', to='clinics.clinic')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visited', to='doctors.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to='patients.patient')),
                ('procedures', models.ManyToManyField(blank=True, to='doctors.procedures')),
            ],
        ),
    ]
