# Generated by Django 5.1.3 on 2024-11-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_procedures_procedure'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='last_visit_procedures',
            field=models.ManyToManyField(blank=True, related_name='past_patient_procedures', to='doctors.procedure'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='next_appointment_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_current_procedure', to='doctors.procedure'),
        ),
    ]
