# Generated by Django 5.1.3 on 2024-11-10 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_phone_number_patient_ssn_last_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_date_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
