# Generated by Django 5.1.3 on 2024-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_procedures_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='brightsmile@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='+234', max_length=14),
        ),
    ]
